// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdknwmgqggtcayrdjvuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indka253bWdxZ2d0Y2F5cmRqdnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzcwMTksImV4cCI6MjA2NjY1MzAxOX0.OxGJHR55Grvpmdk5ECHM6Ixyq-CPHXnUnIMKY2mW24k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});